name: CI
on:
  push:
    branches:
      - "main"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - run: docker compose up -d --build
    - run: echo "done"
    - run: echo "Env ${{ env.ENV_ID }}"
    - run: echo "App ID ${{ secrets.APP_ID }}"
    - name: Stop containers
      if: always()
      run: docker compose down

# publish to docker hub https://medium.com/@avash700/ci-cd-made-easy-github-actions-docker-compose-and-watchtower-60a698d24f27
