FROM ubuntu:latest
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update -y && apt-get upgrade -y

# RUN apt-get install -y qemu-kvm libvirt-dev

RUN apt-get install -y curl net-tools jq
RUN apt-get install -y wget gnupg2 lsb-release build-essential
RUN apt-get autoclean
RUN apt-get autoremove

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | tee /usr/share/keyrings/hashicorp-archive-keyring.asc
RUN echo "deb [ signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc ] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt-get update && apt-get install vagrant -y

RUN cp /etc/apt/sources.list /etc/apt/sources.list~
RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
RUN apt-get update

RUN apt-get build-dep -y vagrant ruby-libvirt
RUN apt-get install -y qemu libvirt-daemon-system ebtables libguestfs-tools libxslt-dev libxml2-dev zlib1g-dev ruby-dev
RUN vagrant plugin install vagrant-libvirt

RUN vagrant --version
RUN vagrant box add --provider libvirt peru/windows-10-enterprise-x64-eval --box-version 20221106.01
RUN vagrant init peru/windows-10-enterprise-x64-eval
COPY startup.sh /
ENTRYPOINT ["/startup.sh"]
