name: CI/CD Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: anaconda-client-env
        environment-file: python_conda_environment.yml
        auto-activate-base: false
    - run: |
        conda info
        conda list
    - name: Run test coverage
      run: python -m pytest --cov=.
    - name: Test with pytest
      run: |
        python -m pytest --cov --cov-report=xml:./reports/coverage/coverage.xml
        # coverage https://smarie.github.io/python-genbadge/
        # https://github.com/marketplace/actions/coverage-badge
        genbadge coverage -o ./reports/coverage/coverage-badge.svg
    - name: Archive coverage badge
      uses: actions/upload-artifact@v4
      with:
        name: reports_dir
        path: ./reports/coverage
        overwrite: true

  publish_release:
    needs: build-linux
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: GitHub context to debug conditional steps
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # so that gh-deploy works

      # retrieve the reports generated previously
      - name: Retrieve reports
        uses: actions/download-artifact@master
        with:
          name: reports_dir
          path: ./reports

#      # Publish the doc and test reports
#      - name: \[not on TAG\] Publish documentation, tests and coverage reports
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads')  # startsWith(matrix.os,'ubuntu')
#        shell: bash -l {0}  # so that conda works
#        run: nox -s publish

      # Publish coverage report
      - name: \[not on TAG\] Create codecov.yaml with correct paths
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads')
        shell: bash
        run: |
          cat << EOF > codecov.yml
          # codecov.yml
          fixes:
            - "/home/runner/work/shadisharba/numerical_tools_and_friends/::" # Correct paths
          EOF
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/coverage/coverage.xml
